language: python

python:
  - 3.6

before_script:
  - bundle install
  - npm install
  - cd ..

install: "pip install -r requirements.txt"

# https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
script:
  - export BOTO_CONFIG=/dev/null
  - npx gulp
  - python manage.py collectstatic --noinput
  # - python manage.py test
